### PR TITLE
github tools: fix fossa workflow file

### PR DESCRIPTION
**Pull request by tools-netlify**
Updates github actions fossa workflow to use environment files instead of deprecated set-env command.

### CODE REVIEW

**Comment by tools-netlify** [comment]
don't merge yet, this requires custom updates

**Review by ehmicky — APPROVED** [review]

**Review by ehmicky — APPROVED** [review]

**Comment by ehmicky** [comment]
@emilyzhang This PR broke this GitHub action.
It seems like this reverted #128 and #118.

**Comment by ehmicky** [comment]
@emilyzhang Would it be ok for me to disable the fossa CI check until this is fixed? Thanks!

**Comment by emilyzhang** [comment]
@ehmicky i went ahead and fixed it in this PR: https://github.com/netlify/zip-it-and-ship-it/pull/241

**Pull request merged**
