### PR TITLE
chore: add packageRules to Renovate config

### PR DESCRIPTION
**Pull request by eduardoboucas**
**- Summary**

Some packages can't be upgraded until we drop support for Node 10. This PR updates the Renovate config to that effect.

**- Test plan**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

🐘

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
FYI this will auto close https://github.com/netlify/zip-it-and-ship-it/pull/494 and https://github.com/netlify/zip-it-and-ship-it/pull/497, but we should still update `p-map` to `v4` and `yargs` to `v16`

**Comment by erezrokah** [comment]
We can use something like https://github.com/netlify/renovate-config/blob/21eae43b07e39ac00251a6411fe297e01e658fbe/default.json#L27

**Comment by eduardoboucas** [comment]
Oh, good point! I'll address that separately. Thanks!

**Comment by eduardoboucas** [comment]
@erezrokah Added that in https://github.com/netlify/zip-it-and-ship-it/pull/501/commits/6d97ebcf576aa129a9393d06d1cd5c465bbfc44b.

**Review by erezrokah — APPROVED** [review]
🚀

**Pull request merged**
