### PR TITLE
chore: support Node 15

### PR DESCRIPTION
**Pull request by ehmicky**
Part of https://github.com/netlify/team-dev/issues/1

This tests Node 15 in CI.

### CODE REVIEW

**Comment by ehmicky** [comment]
It seems like creating the zip archive fails on [Node `15.6.0`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#15.6.0) but not on Node `15.5.0`.
What's odd is that most of the files in the archive are correct, except the entry point.
The entry point appears to be a corrupted archive. I am wondering if there is some bug in

**Comment by erezrokah** [comment]
> The entry point appears to be a corrupted archive. I am wondering if there is some bug in Node.js? Upgrading a minor version should never create failures.

That's very interesting - especially since our customers should experience the same

**Comment by ehmicky** [comment]
In the meantime, I think we should still be able to merge this, what do you think?

**Comment by erezrokah** [comment]
> In the meantime, I think we should still be able to merge this, what do you think?

Yes I agree.

**Review by erezrokah — APPROVED** [review]

**Comment by ehmicky** [comment]
Issue for Node `15.6.0` at https://github.com/netlify/zip-it-and-ship-it/issues/311

**Pull request merged**
