### PR TITLE
feat: add new top-level `schedule` property

### PR DESCRIPTION
**Pull request by eduardoboucas**
**- Summary**

Currently, any schedule data is surfaced in the result of `zipFunction` and `zipFunctions` as `config.schedule`. This PR adds a new top-level `schedule` property, which contains the same value.

This property will be useful when we introduce the in-code config declarations, because we'll be able to merge schedule data coming from the two types of sources and decide which one takes priority.

**- Test plan**

New test added.

### CODE REVIEW

**Review by netlify-team-account-1 — APPROVED** [review]
Loving these super small PRs, really easy to review ^^

We already have a test for `schedule`: https://github.com/netlify/zip-it-and-ship-it/blob/main/tests/main.js#L2241
What does the new test give us? (not blocking obvsly, the more tests the merrier)

**Comment by eduardoboucas** [comment]
> Loving these super small PRs, really easy to review ^^
> 
> We already have a test for `schedule`: https://github.com/netlify/zip-it-and-ship-it/blob/main/tests/main.js#L2241 What does the new test give us? (not blocking obvsly, the more tests the merrier)

The other test was primarily built to assert the creation of a manifest file. I wanted to have a test specific for schedules, which will be useful once we add the in-code annotations. We can either remove the schedule assertions from the test you linked, or we can keep them because it's fine to have that assertion duplicated. What would you prefer?

**Comment by eduardoboucas** [comment]
@netlify-team-account-1 the review got stale when I fixed the merge conflict - could you ✅  again, please?

**Review by minivan — APPROVED** [review]
LGTM

**Pull request merged**
