### PR TITLE
fix: add `prisma` CLI to EXCLUDED_PEER_DEPENDENCIES

### PR DESCRIPTION
**Pull request by Jolg42**
**- Summary**

Prisma is going to rename the CLI package from `@prisma/cli` to `prisma`, so the excluded list needs to be updated with that new package name (and keep the older names for retro-compatibility).

**- Test plan**

**- Description for the changelog**

add `prisma` CLI to EXCLUDED_PEER_DEPENDENCIES

**- A picture of a cute animal (not mandatory but encouraged)**

juuiev6a6oyy

### CODE REVIEW

**Review by ehmicky — APPROVED** [review]
Thanks for the PR @joelcloralt!

**Comment by Jolg42** [comment]
That was fastttt! 🚀 Thanks ❤️

**Comment by Jolg42** [comment]
@ehmicky Do you know how long it takes for it to be used on Netlify's servers / deployment? (Is it automated?)

**Comment by ehmicky** [comment]
We try to avoid releases on Fridays, so this should be in production on Monday :+1:

**Pull request merged**
